# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v3.2.0
  hooks:
    - id: trailing-whitespace
    - id: end-of-file-fixer
    - id: check-yaml
    - id: check-added-large-files
    - id: check-json
    - id: detect-private-key
    - id: check-added-large-files
      args: ['--maxkb=1024']
- repo: https://github.com/psf/black-pre-commit-mirror
  rev: 24.4.2
  hooks:
    - id: black-jupyter
      language_version: python3.10
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.5.5
  hooks:
    - id: ruff
    - id: ruff-format
