base_model_name: "microsoft/Phi-3-mini-4k-instruct"
resume_from_checkpoint: "Phi-3-mini-4k-instruct-qlora-law/checkpoint-1500"
output_dir : "Phi-3-mini-4k-instruct-qlora-law"
DEBUG: True
dataset_name: "HFforLegal/case-law"
dataset_split: "us"
seq_length: 1024